### ISSUE TITLE
[BUG] Error #01: Error 1146: Table 'get5.user' doesn't exist

### ISSUE THREAD

**Issue by tydaytygx** [FlowingSPDG/get5-web-go#184]
Is there any guide to setup/modify the database?
```
Error #01: Error 1146: Table 'get5.user' doesn't exist
```

**Comment by tydaytygx** [comment]
Should I need to follow the python version database guide to create a database?
Or I just need to create a database called get5 on mysql?
Thanks for your apply!

**Comment by FlowingSPDG** [comment]
Hi, If you have get5 database from Python' version, you should migrate it for go by using this : https://github.com/FlowingSPDG/get5-web-go/tree/master/migration
(build) : https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-migration
or you can create new "get5" and migrate it.

btw, I recommend you to make a backup of original python get5-web table just in case you want to use Py's get5 again!

**Comment by tydaytygx** [comment]
> 
> 
> Hi, If you have get5 database from Python' version, you should migrate it for go by using this : https://github.com/FlowingSPDG/get5-web-go/tree/master/migration
> (build) : https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-migration
> or you can create new "get5" and migrate it.
> 
> btw, I recommend you to make a backup of original python get5-web table just in case you want to use Py's get5 again!

Thanks for your apply! But now I consider to make a new brand new database, is the database creating steps included in the get5-web-go version? By the way, I use Mysql and root with a new database called get5 with no tables. Should I need to create the tables manually? Thank you!

**Comment by FlowingSPDG** [comment]
Yes, its included inside of migration binary : https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-migration
description : https://github.com/FlowingSPDG/get5-web-go/tree/master/migration

you should be able to use that new get5 DB without any changes!

**Comment by tydaytygx** [comment]
> 
> 
> Yes, its included inside of migration binary : https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-migration
> description : https://github.com/FlowingSPDG/get5-web-go/tree/master/migration
> 
> you should be able to use that new get5 DB without any changes!

Seems I missed a whole step of creating the tables, thank you! But where is the execute file ```migrate```?
I followed the schema and manually created the table.
The ```description : https://github.com/FlowingSPDG/get5-web-go/tree/master/migration``` could be placed to the ```Readme#How to use```
But there is another error, the web told me that the team has registered successfully, but switching to the ```teams``` tag telling no teams found, no data changes in the database(the database has tables just like the schema), is there something wrong? (the 200 POST is successful)
```
2021/03/22 19:58:26 CreateTeam
[GIN] 2021/03/22 - 19:58:26 | 200 |    80.01108ms |       127.0.0.1 | POST     /api/v1/team/create
```

**Comment by tydaytygx** [comment]
Oh I notice that you change the ```./migrate``` to ```./migration``` in the binary.
The team function work like a charm using your migration. Thank you!
I shutdown all my scrds, but the adding the server seems still not working?
```
Error #01: JSON Format invalid
```
