### ISSUE TITLE
[API] More detailed config

### ISSUE THREAD

**Issue by FlowingSPDG** [FlowingSPDG/get5-web-go#88]
Support these keys : https://github.com/splewis/get5-web/blob/8c1012c9563583353b9486a6590227855547e275/instance/prod_config.py.default

**Comment by FlowingSPDG** [comment]
```
SQLALCHEMY_TRACK_MODIFICATIONS = False
USER_MAX_SERVERS = 10  # Max servers a user can create
USER_MAX_TEAMS = 100  # Max teams a user can create
USER_MAX_MATCHES = 1000  # Max matches a user can create
ADMINS_ACCESS_ALL_MATCHES = False  # Whether admins can always access any match admin panel

# You may set the server to allow allow whitelisted steamids to login.
# By default any user can login and create teams/servers/matches.
WHITELISTED_IDS = []

# Admins will have extra access to create "public" teams, and if ADMINS_ACCESS_ALL_MATCHES
# is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match.
ADMIN_IDS = []

# The spectator value is for observers and other personnel 
# that need to be able to join the server, while the game is live or in the warmup. And would otherwise get kicked by the game.
SPECTATOR_IDS = []

# This specifies how much spectators are needed to ready up to get the match started/live
# this is an optional configuration
# MIN_SPECTATORS_TO_READY = 0

# This overrides the default way to build the config URL that get appended to the get5_loadmatch_url rcon command.
# Uncomment and use this if you need to set another ip for your get5 instance than the public ip you're using get5 with
# in your browser.
# GET5_URL_OVERRIDE = '127.0.0.1'
```

**Comment by FlowingSPDG** [comment]
MAPLIST : Done✅ https://github.com/FlowingSPDG/get5-web-go/issues/87

**Comment by FlowingSPDG** [comment]
https://github.com/FlowingSPDG/get5-web-go/tree/more_config

**Comment by FlowingSPDG** [comment]
```
USER_MAX_SERVERS = 10  # Max servers a user can create
USER_MAX_TEAMS = 100  # Max teams a user can create
USER_MAX_MATCHES = 1000  # Max matches a user can create
```
https://github.com/FlowingSPDG/get5-web-go/commit/86b4ee5dbcd3b446c5d1455e8594b9171e6c1daa

**Comment by FlowingSPDG** [comment]
```
# You may set the server to allow allow whitelisted steamids to login.
# By default any user can login and create teams/servers/matches.
WHITELISTED_IDS = []

# Admins will have extra access to create "public" teams, and if ADMINS_ACCESS_ALL_MATCHES
# is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match.
ADMIN_IDS = []

# The spectator value is for observers and other personnel 
# that need to be able to join the server, while the game is live or in the warmup. And would otherwise get kicked by the game.
SPECTATOR_IDS = []

# This specifies how much spectators are needed to ready up to get the match started/live
# this is an optional configuration
# MIN_SPECTATORS_TO_READY = 0

# This overrides the default way to build the config URL that get appended to the get5_loadmatch_url rcon command.
# Uncomment and use this if you need to set another ip for your get5 instance than the public ip you're using get5 with
# in your browser.
# GET5_URL_OVERRIDE = '127.0.0.1'
```

those options are not popular for most users(and me) imo,so priority is not so high

**Comment by FlowingSPDG** [comment]
https://github.com/FlowingSPDG/get5-web-go/pull/131

**Comment by tydaytygx** [comment]
> 
> 
> ```
> SQLALCHEMY_TRACK_MODIFICATIONS = False
> USER_MAX_SERVERS = 10  # Max servers a user can create
> USER_MAX_TEAMS = 100  # Max teams a user can create
> USER_MAX_MATCHES = 1000  # Max matches a user can create
> ADMINS_ACCESS_ALL_MATCHES = False  # Whether admins can always access any match admin panel
> 
> # You may set the server to allow allow whitelisted steamids to login.
> # By default any user can login and create teams/servers/matches.
> WHITELISTED_IDS = []
> 
> # Admins will have extra access to create "public" teams, and if ADMINS_ACCESS_ALL_MATCHES
> # is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match.
> ADMIN_IDS = []
> 
> # The spectator value is for observers and other personnel 
> # that need to be able to join the server, while the game is live or in the warmup. And would otherwise get kicked by the game.
> SPECTATOR_IDS = []
> 
> # This specifies how much spectators are needed to ready up to get the match started/live
> # this is an optional configuration
> # MIN_SPECTATORS_TO_READY = 0
> 
> # This overrides the default way to build the config URL that get appended to the get5_loadmatch_url rcon command.
> # Uncomment and use this if you need to set another ip for your get5 instance than the public ip you're using get5 with
> # in your browser.
> # GET5_URL_OVERRIDE = '127.0.0.1'
> ```
Thanks for your hard-working of recreation! Is the spectator and other detail config done now?
